### ISSUE TITLE
Paper full-text (manual upload)

### ISSUE THREAD

**Issue by Mnaukal** [smartarch/robin#3]
We have an option to automatically download full-text PDF of the publication, but it is disabled for some reason (is it API limits?). Tomas suggests an option to manually upload the PDF to the server.

**Comment by MiladAbdullah** [comment]
There are two ways to get the full text:
* `Check from URL`: this is done automatically if the DOI has a URL link, if not, this option will be disabled.
* `Upload`: the user can upload a pdf, and it will be visible to all reviewers of the same mapping.
